version: "3.7"
services:
  postgres-opi-server:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ${OPI_PG_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "21432:5432"
  # Bitcoind service is now conditional based on DEPLOY_BITCOIND environment variable
  ${DEPLOY_BITCOIND:+bitcoind}:
    image: ${BITCOIND_IMAGE}
    restart: always
    volumes:
      - ${OPI_BITCOIND_PATH}:/usr/local/bitcoind
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWD=${BITCOIN_RPC_PASSWD}
      - BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT:-8332}
      - BITCOIN_ZMQ_PORT=${BITCOIN_ZMQ_PORT:-18543}
      - BITCOIN_DB_CACHE=${BITCOIN_DB_CACHE:-12000}
    ports:
      - "${BITCOIN_RPC_PORT:-8332}:${BITCOIN_RPC_PORT:-8332}"
      - "${BITCOIN_ZMQ_PORT:-18543}:${BITCOIN_ZMQ_PORT:-18543}"
  meta-protocol-indexer:
    image: ${OPI_IMAGE}
    restart: always
    command: 'bash -c "cd /usr/local/OPI/modules/main_index && node --max-old-space-size=12288 index.js"'
    volumes:
      - ./configs/main_index/.env:/usr/local/OPI/modules/main_index/.env
      - ${ORD_DATADIR}:/ord_data
      - ${BITCOIN_CHAIN_FOLDER}:/bitcoind/datadir
    depends_on:
      postgres-opi-server:
        condition: service_healthy
      # Make bitcoind dependency conditional
      ${DEPLOY_BITCOIND:+bitcoind}:
        condition: service_started
  brc20-indexer:
    image: ${OPI_IMAGE}
    restart: always
    command: 'bash -c "cd /usr/local/OPI/modules/brc20_index && python brc20_index.py"'
    volumes:
      - ./configs/brc20_index/.env:/usr/local/OPI/modules/brc20_index/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  brc20-api:
    image: ${OPI_IMAGE}
    command: 'bash -c "cd /usr/local/OPI/modules/brc20_api && node api.js"'
    volumes:
      - ./configs/brc20_api/.env:/usr/local/OPI/modules/brc20_api/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  bitmap-indexer:
    image: ${OPI_IMAGE}
    restart: always
    command: 'bash -c "cd /usr/local/OPI/modules/bitmap_index && python bitmap_index.py"'
    volumes:
      - ./configs/bitmap_index/.env:/usr/local/OPI/modules/bitmap_index/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  bitmap-api:
    image: ${OPI_IMAGE}
    command: 'bash -c "cd /usr/local/OPI/modules/bitmap_api && node api.js"'
    volumes:
      - ./configs/bitmap_api/.env:/usr/local/OPI/modules/bitmap_api/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  sns-indexer:
    image: ${OPI_IMAGE}
    restart: always
    command: 'bash -c "cd /usr/local/OPI/modules/sns_index && python sns_index.py"'
    volumes:
      - ./configs/sns_index/.env:/usr/local/OPI/modules/sns_index/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  sns-api:
    image: ${OPI_IMAGE}
    command: 'bash -c "cd /usr/local/OPI/modules/sns_api && node api.js"'
    volumes:
      - ./configs/sns_api/.env:/usr/local/OPI/modules/sns_api/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  pow20-indexer:
    image: ${OPI_IMAGE}
    restart: always
    command: 'bash -c "cd /usr/local/OPI/modules/pow20_index && python pow20_index.py"'
    volumes:
      - ./configs/pow20_index/.env:/usr/local/OPI/modules/pow20_index/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
  pow20-api:
    image: ${OPI_IMAGE}
    command: 'bash -c "cd /usr/local/OPI/modules/pow20_api && node api.js"'
    volumes:
      - ./configs/pow20_api/.env:/usr/local/OPI/modules/pow20_api/.env
    depends_on:
      postgres-opi-server:
        condition: service_healthy
